### ISSUE TITLE
simple example in README with public hub

### ISSUE THREAD

**Issue by allenday** [vrypan/fario#2]
I've been trying to connect to the public hub `hub.pinata.cloud` and getting errors for all combinations of adding/omitting `--hub` and `--ssl`, and adding/omitting an explicit `:443` for ssl.

After reading `--help` for fario-fid-byname, I thought this command should work:

```
# fario-fid-byname --help
usage: fario-fid-byname [-h] [--version] [--hub HUB] [--ssl] [-v] username

Get a user's fid

positional arguments:
  username       Cast text

options:
  -h, --help     show this help message and exit
  --version      show program's version number and exit
  --hub HUB      Use the hub at <ADDRESS>. Ex. --hub 192.168.1.1:2283
  --ssl          Use SSL
  -v, --verbose  increase output verbosity
# fario-fid-byname --hub hub.pinata.cloud:443 --ssl allenday
E0520 07:02:21.745790385    8053 hpack_parser.cc:999]                  Error parsing 'content-type' metadata: invalid value
Traceback (most recent call last):
  File "/usr/local/bin/fario-fid-byname", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fario/fario_fid_byname.py", line 22, in main
    ret  = hub.GetUsernameProof(args.username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/farcaster/HubService.py", line 162, in GetUsernameProof
    return self._stub.GetUsernameProof(UsernameProofRequest(name=bytes(name,'ascii')))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/grpc/_channel.py", line 1161, in __call__
    return _end_unary_response_blocking(state, call, False, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/grpc/_channel.py", line 1004, in _end_unary_response_blocking
    raise _InactiveRpcError(state)  # pytype: disable=not-instantiable
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = "Stream removed"
	debug_error_string = "UNKNOWN:Error received from peer  {created_time:"2024-05-20T07:02:21.746186885+00:00", grpc_status:2, grpc_message:"Stream removed"}"
>
```

**Comment by allenday** [comment]
This works :)

```
# cat ~/.fario
hub=nemes.farcaster.xyz:2283
user_fid=
user_key=
app_fid=
app_key=
signer=
op_eth_provider=mainnet.optimism.io:443
ssl=true
# fario-fid-byname allenday
12037
```

**Comment by vrypan** [comment]
Hi @allenday. So, the problem was that you did not have a .fario config file? Or was it that there is no option to set op_eth_provider?
